### ISSUE TITLE
`bool` is not rendered in the same style as other builtins

### ISSUE THREAD

**Issue by da1910** [pyansys/pyansys-sphinx-theme#15]
Parameters with type `bool` are rendered in the standard blue link style, whilst other types are rendered in the conventional gold colour, this looks odd:

![image](https://user-images.githubusercontent.com/12086549/146532786-efb0d95a-cca0-4678-af64-0e77c663aa17.png)

**Comment by akaszynski** [comment]
Still need to look into this...
