### ISSUE TITLE
There is not much distintion between output code and input code.

### ISSUE THREAD

**Issue by germa89** [pyansys/pyansys-sphinx-theme#26]
Currently there is not much distinction between ``.. code::`` blocks and ``.. parsed-literal::`` (which are used by jupyter exporter for console output).

I wonder if there is a better way to reflect that one is input, and the other is output.

The following code:

```rst

.. code:: ipython3

    # Calling OpenAI Cartpole environment and generating folders for backup.
    env_name = 'CartPole-v0'
    tmp_path = tempfile.gettempdir()
    
    output_path_gym = os.path.join(tmp_path, 'gym_cartpole_results', str(uuid4())) 
    output_name_gym = 'gym_cartpole_00'
    
    if not os.path.exists(output_path_gym):
        os.makedirs(output_path_gym)
    print(f'Writing model in: {output_path_gym}')


.. parsed-literal::

    Writing model in: C:\Users\gayuso\AppData\Local\Temp\gym_cartpole_results\e22e8cab-251d-4d8a-b698-bcc9ac841ac9

```

Shows as:

![image](https://user-images.githubusercontent.com/28149841/154073303-1ec7c1e4-d7a0-4a8d-894c-f06bd84e9021.png)

**Comment by akaszynski** [comment]
Consider using a different [pygments](https://pygments.org/) theme.

**Comment by akaszynski** [comment]
Closing. This can be addressed at the library level.
